Restored emu directory

diff --git a/bin/cloudemu b/bin/cloudemu
--- a/bin/cloudemu
+++ b/bin/cloudemu
@@ -1,11 +1,13 @@
 #!/bin/bash
 
-pluginname=REPLACELBPPLUGINDIR
+pluginname=weather4lox
 
 PATH="/sbin:/bin:/usr/sbin:/usr/bin:$LBHOMEDIR/bin:$LBHOMEDIR/sbin"
 
 ENVIRONMENT=$(cat /etc/environment)
 export $ENVIRONMENT
+
+echo "Loxone Weather Emulator started..."
 
 # Check for WLAN adapter
 #CHECKWLAN=`ifconfig | grep -c -i wlan0`
@@ -24,60 +26,70 @@ export $ENVIRONMENT
 # Check if we figured out an IP
 OWNIP=`perl $LBHOMEDIR/bin/plugins/$pluginname/ownip.pl`
 if [ -z $OWNIP ]; then
-	echo "Cannot figure out a valid IP address. Giving up."
-	exit 1
+    echo "Cannot figure out a valid IP address. Giving up."
+    exit 1
 fi
 
 # Check if own IP is reachable
 PING=`ping -c1 $OWNIP`
 if [ $? -ne 0 ]; then
-	echo "Cannot reach my own IP address $OWNIP. Giving up."
-	exit 1
+    echo "Cannot reach my own IP address $OWNIP. Giving up."
+    exit 1
 fi
 
 # Check for DNSMasq Plugin
-CHECKDNSMASQ=`cat $LBSDATA/plugindatabase.dat | grep -c -i DNSmasq`
+CHECKDNSMASQ=`grep -c '"title" : "DNSmasq"' "$LBSDATA/plugindatabase.json"`
 
 # Enable DNSMasq Config
 case "$1" in
 
   enable)
-	if [ $CHECKDNSMASQ -eq 1 ]; then
-		echo "Found installed DNSMasq Plugin. Will do no changes to DNSMasq configuration."
-	else
-		echo "My own IP is $OWNIP. Redirecting weather.loxone.com to $OWNIP."
-		touch /etc/dnsmasq.d/$pluginname.conf > /dev/null 2>&1
-		echo "Enabling DNSMasq Configuration for WU4Lox"
-		echo "address=/weather.loxone.com/$OWNIP" > /etc/dnsmasq.d/$pluginname.conf
-		echo "address=/weather-beta.loxone.com/$OWNIP" >> /etc/dnsmasq.d/$pluginname.conf
-		service dnsmasq restart > /dev/null 2>&1
-	fi
-	# Enable Apache Config
-	echo "Enabling Apache2 Configuration for WU4Lox"
-	a2ensite 001-$pluginname > /dev/null 2>&1
-	service apache2 reload > /dev/null 2>&1
-        exit 0
-        ;;
+    if [ $CHECKDNSMASQ -eq 1 ]; then
+        echo "Found installed DNSMasq Plugin. Will add changes to existing DNSMasq configuration."
+        echo "  address=/weather.loxone.com/$OWNIP > /etc/dnsmasq.d/$pluginname.conf"
+        echo "  address=/weather-beta.loxone.com/$OWNIP >> /etc/dnsmasq.d/$pluginname.conf"
+
+        sudo sh -c "echo 'address=/weather.loxone.com/$OWNIP' > /etc/dnsmasq.d/$pluginname.conf"
+        sudo sh -c "echo 'address=/weather-beta.loxone.com/$OWNIP' >> /etc/dnsmasq.d/$pluginname.conf"
+        sudo service dnsmasq restart > /dev/null 2>&1
+    else
+        echo "Enabling DNSMasq Configuration for WU4Lox (without installed DNSMasq Plugin)."
+        echo "My own IP is $OWNIP. Redirecting weather.loxone.com to $OWNIP."
+
+        sudo sh -c "touch /etc/dnsmasq.d/$pluginname.conf" > /dev/null 2>&1
+        sudo sh -c "echo 'address=/weather.loxone.com/$OWNIP' > /etc/dnsmasq.d/$pluginname.conf"
+        sudo sh -c "echo 'address=/weather-beta.loxone.com/$OWNIP' >> /etc/dnsmasq.d/$pluginname.conf"
+        sudo service dnsmasq restart > /dev/null 2>&1
+    fi
+    # Enable Apache Config
+    echo "Enabling Apache2 Configuration for WU4Lox"
+    sudo a2ensite 001-$pluginname > /dev/null 2>&1
+    sudo service apache2 reload > /dev/null 2>&1
+    exit 0
+  ;;
 
   disable)
-	# Disable DNSMasq Config
-	if [ $CHECKDNSMASQ -eq 1 ]; then
-	echo "Disabling DNSMasq Configuration for WU4Lox"
-		echo "Found installed DNSMasq Plugin. Will do no changes to DNSMasq configuration."
-	else
-		rm /etc/dnsmasq.d/$pluginname.conf > /dev/null 2>&1
-		service dnsmasq restart > /dev/null 2>&1
-	fi
-	# Disable Apache Config
-	echo "Disabling Apache2 Configuration for WU4Lox"
-	a2dissite 001-$pluginname > /dev/null 2>&1
-	service apache2 reload > /dev/null 2>&1
-        exit 0
-        ;;
+    # Disable DNSMasq Config
+    if [ $CHECKDNSMASQ -eq 1 ]; then
+        echo "Found installed DNSMasq Plugin. Will do no changes to DNSMasq configuration."
+        echo "  removing /etc/dnsmasq.d/$pluginname.conf"
+
+        sudo rm /etc/dnsmasq.d/$pluginname.conf > /dev/null 2>&1
+    else
+        echo "Disabling DNSMasq Configuration for WU4Lox"
+        sudo rm /etc/dnsmasq.d/$pluginname.conf > /dev/null 2>&1
+        sudo service dnsmasq restart > /dev/null 2>&1
+    fi
+    # Disable Apache Config
+    echo "Disabling Apache2 Configuration for WU4Lox"
+    sudo a2dissite 001-$pluginname > /dev/null 2>&1
+    sudo service apache2 reload > /dev/null 2>&1
+    exit 0
+  ;;
 
   *)
-        echo "Usage: $0 [enable|disable]" >&2
-        exit 3
+    echo "Usage: $0 [enable|disable]" >&2
+    exit 3
   ;;
 
 esac
